---
title: >-
    Linewidth reduced cascaded Raman fiber lasers and their harmonic conversion
    for visible laser sources
author:
    - "**Sarthak Dash**"
    - Rashmita Deheri
    - VR Supradeepa
issued: 2024
doi: https://doi.org/10.1364/OE.524166
type: journal-article
journal-title: Optics Express
toc: false
bibliography: publications.bib
bibliographystyle: ieee.csl
nocite: |
    @dashLinewidthReducedCascaded2024a
---

:::{.callout-tip collapse="true" title="Citation" icon="false"}
::: {#refs}
:::
:::

:::{.callout-note collapse="false" title="Abstract"}
Cascaded Raman Fiber Lasers (CRFLs) are wavelength versatile sources that can provide power at any wavelength in the Near-Infrared (NIR) region. Conventional CRFLs with broadband feedback are widely wavelength tunable but have broad line widths. A feedback mechanism must be used to reduce the broadening of the linewidth without compromising the wavelength tunability. Here, we propose to use a dual feedback mechanism that combines broadband feedback at all wavelengths, using a flat cleave, with filtered feedback at a desired wavelength due to a grating filter. This allows substantial linewidth reduction of CRFLs up to the 6th Raman shifts, from 1100 nm to 1500 nm, and can be extended further. Significantly reduced linewidth with multi-watt in-band output power is achieved with fine wavelength tuning within each Raman Stokes band using a fixed wavelength pump. As an application of linewidth narrowed output, we performed frequency doubling of CRFL output to generate over 100 mW of wavelength tunable yellow-green and yellow output with enhanced efficiency.
:::

