---
title: >-
  Widely tunable visible pulsed cascaded raman fiber laser source
author:
  - Abhigyan Goswami
  - "**Sarthak Dash**"
  - Rashmita Deheri
  - VR Supradeepa
issued: 2024
doi: https://doi.org/10.1117/12.3000916
type: proceedings-article
journal-title: "Nonlinear Frequency Generation and Conversion: Materials and Devices XXIII"
toc: false
bibliography: publications.bib
bibliographystyle: ieee.csl
nocite: |
  @goswamiWidelyTunableVisible2024
---

:::{.callout-tip collapse="true" title="Citation" icon="false"}
::: {#refs}
:::
:::

:::{.callout-note collapse="false" title="Abstract"}
We have generated a visible laser by second harmonic generation from a pulsed Cascaded Raman fiber Lasers (CRFL) continuously tunable in 1060nm-1600nm, using type-I LBO. To eliminate the requirement of precise synchronization and control, we employed a passive Q-switching mechanism for the Yb laser pumping the Raman module. The pump is made continuously tunable in Yb-band with wavelength dependent feedback in the Q-switched cavity ensuring continuous wavelength tunability of generated Raman Stokes. We utilized a large mode-area amplifier to amply pulse-energy without introducing temporal instability and optimized Raman module for efficient pump conversion. We demonstrated a widely tunable visible laser with approximately μJ pulse-energy and approximately 20 − 65kHz repetition-rate, 40-200ns pulse duration. This is the first demonstration of a high pulse energy nanosecond laser continuously tunable in 530nm-600nm making it a versatile laser source for numerous biomedical applications. The wavelength tunable range can be extended to 700nm by utilizing type-II LBO.
:::
