---
title: >-
  Photoacoustic Spectroscopy Using a Widely Tunable Pulsed Cascaded Raman Fiber Laser
author:
  - Abhigyan Goswami
  - Swathi Padmanabhan
  - "**Sarthak Dash**"
  - Jaya Prakash
  - VR Supradeepa
issued: 2025
doi: https://opg.optica.org/abstract.cfm?URI=CLEO_Europe-2025-cj_14_4
type: conference-proceedings
journal-title: Conference on Lasers and Electro-Optics/Europe (CLEO/Europe 2025) and European Quantum Electronics Conference (EQEC 2025)
toc: false
bibliography: publications.bib
bibliographystyle: ieee.csl
nocite: |
  @goswamiPhotoaccousticSpectroscopy2025
---

:::{.callout-tip collapse="true" title="Citation" icon="false"}
::: {#refs}
:::
:::

:::{.callout-note collapse="false" title="Abstract"}
Nanosecond pulsed laser sources are widely used in many biomedical imaging applications, including photoacoustic imaging (PAI) [1]. Wide wavelength tunability of the source is essential for imaging multiple endogenous chromophores (optical absorbers inside tissues). Pulsed cascaded Raman fiber lasers (CRFL) can provide an efficient method to generate high pulse energy laser sources outside the conventional rare-earth emission bands and their high harmonic bands [2]. There were a few demonstrations of PAI using CRFL [1]. The CRFLs pumped with a fix wavelength laser source, generated only discrete wavelengths associated with Raman shifts. Lack of continuous wavelength tunability hinders use of such sources in spectroscopic applications.
:::
