---
title: >-
  Brillouin-assisted generation and demultiplexing of widely tunable high-repetition rate 1064 nm optical frequency combs with applications in spectral beam combining
author:
  - Soubhik Pal
  - Shilpi Arora
  - "**Sarthak Dash**"
  - CG Lakshmi
  - VR Supradeepa
issued: 2025
doi: https://doi.org/10.1364/oe.560505
type: journal-article
journal-title: Optics Express
toc: false
bibliography: publications.bib
bibliographystyle: ieee.csl
nocite: |
  @palBrillouinassistedGenerationDemultiplexing2025
---

:::{.callout-tip collapse="true" title="Citation" icon="false"}
::: {#refs}
:::
:::

:::{.callout-note collapse="false" title="Abstract"}
The generation and demultiplexing of high-repetition-rate optical frequency combs (OFC) have many applications, including optical metrology, microwave signal generation, and high-resolution spectroscopy. One such novel application is in generating cost-effective seed sources for spectral beam combination (SBC) of multiple fiber laser modules. SBC enables high power-scaling in hundreds of kilowatts, but it requires multiple laser diodes as seed sources, and each source needs its own individual temperature and wavelength stabilization, increasing cost and system complexity. De-multiplexed OFC lines can provide efficient seed sources for SBC, requiring a single laser diode as a seed source. Seed sources at 1 μm are important due to the availability of efficient gain media such as ytterbium-doped fiber amplifiers (YDFA). However, due to the lack of components required for generating high-repetition-rate combs(>40 GHz) and high-resolution demultiplexing of OFCs at 1 μm range, such applications are limited. In this work, we demonstrate the generation of tunable high repetition-rate 1 μm OFCs by selective amplification of low-repetition-rate comb lines. Two combs with repetition rates ranging from 9-13 GHz are counter-propagated in a nonlinear Brillouin gain medium. By suitably changing the repetition rates of the combs through selective Brillouin gain due to the Vernier effect, amplified combs with user-defined line spacing of up to 48 GHz were obtained. The spacing could also be tuned in fine steps of 100 MHz or lower. The de-interleaved combs could be demultiplexed using a grating-based demultiplexer. Such sources promise to be a compact replacement for SBC seed sources while also having applications in arbitrary waveform generation and optical metrology.
:::
